### ISSUE TITLE
Проверить гипотезу об автомате

### ISSUE THREAD

**Issue by MrsBadger** [robot-lab/judyst-research#5]
# Idea proposal

## В чём заключается идея

Необходимо создать некоторый конечный автомат для поиска сущностей, называемых ссылкой, способный определить их и извлечь из сущности ссылку в некоторой “нормальной форме”.
(Данная задача может быть неудачной)

**Comment by Vasar007** [comment]
Из-за специфики регулярных выражений и присутствующих в них средствах пост-обработки данных, невозможно создать эффективный конечный автомат, ДКА, который бы работал за линейное время. Для достижения этой цели придётся полностью переделывать модуль анализа текста, что потребует дополнительных трудозатрат.

При прямом преобразовании текущих регулярных выражений в КА мы получаем e-НКА, трудоёмкость которого может достигать экспоненциальной сложности. В связи с этим, данная задача не принесёт никакого прогресса в проект (при незатратном подходе с переиспользованием текущей базы кода библиотеки для анализа текстов).
